# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'NotificationContent' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for NotificationContent

end

target 'NotificationService' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for NotificationService

end

target 'SnipProject' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # add pods for desired Firebase products
  # https://firebase.google.com/docs/ios/setup#available-pods
  pod 'Firebase/Firestore'
  pod 'Firebase/Auth'

  # Pods for SnipProject

  target 'SnipProjectTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
